TuyenDungCNTT/Areas/Admin/Controllers/NhaTuyenDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.Employer;

namespace TuyenDungCNTT.Areas.Admin.Controllers
{
    public class NhaTuyenDungController : BaseController
    {
        NhaTuyenDungDao dao;

        public NhaTuyenDungController()
        {
            dao = new NhaTuyenDungDao();
        }

        // GET: Admin/TuyenDung
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetPaging(string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await dao.GetList(request);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(EmployerEdit member)
        {
            if (ModelState.IsValid)
            {
                var result = await dao.Create(member);
                if (result > 0)
                {
                    SetAlert("Tạo nhà tuyển dụng thành công", "success");
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Mã nhà tuyển dụng đã tồn tại");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mã nhà tuyển chưa trùng với mã tài khoản đăng ký nhà tuyển dụng");
                }
                else
                {
                    SetAlert("Đã có lỗi xảy ra. Vui lòng thử lại", "error");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Detail(int id)
        {
            var member = await dao.GetById(id);
            ViewBag.MaNTD = member.MaNTD;
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maNTD)
        {
            var result = await dao.Delete(maNTD);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.BaiViet;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.User;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class BaiVietController : BaseController
    {
        private readonly BaiVietDao dao;

        public BaiVietController()
        {
            dao = new BaiVietDao();
        }

        // GET: NhaTuyenDung/BaiViet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool trangThai, string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = dao.GetList(request, trangThai, session.Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(BaiVietCreate member)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.Create(member, Server, session.Id);
                if (result > 0)
                {
                    SetAlert("Tạo bài viết thành công", "success");
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tên bài viết đã tồn tại");
                }
                else
                {
                    SetAlert("Đã có lỗi xảy ra. Vui lòng thử lại", "error");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var member = await dao.GetById(id);
            ViewBag.MaBaiViet = member.MaBaiViet;
            ViewBag.AnhChinh = member.AnhChinh;
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(BaiVietEdit member)
        {
            var item = await dao.GetById(member.MaBaiViet);
            ViewBag.MaBaiViet = item.MaBaiViet;
            ViewBag.AnhChinh = item.AnhChinh;
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.UpdateBaiViet(member, Server, session.Id);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maBaiViet)
        {
            var result = await dao.Delete(maBaiViet);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }

        public ActionResult ChoDuyet()
        {
            return View();
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.User;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class BaseController : Controller
    {
        protected UserLogin UserLogin()
        {
            return (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            if (session == null)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new { controller = "Login", action = "Index" }));
            }
            else
            {
                var userLogin = new NhaTuyenDungDao().GetNhaTuyenDung(session.Id);
                TempData["AnhDaiDien"] = userLogin.AnhDaiDien;
            }
            base.OnActionExecuting(filterContext);
        }

        protected void SetAlert(string message, string type)
        {
            TempData["Notify"] = message;
            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if (type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.Employer;
using TuyenDungCNTT.Models.ViewModels.User;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class HomeController : BaseController
    {
        private readonly NhaTuyenDungDao nhatuyendungDao;
        private readonly TinTuyenDungDao tintuyendungDao;

        public HomeController()
        {
            nhatuyendungDao = new NhaTuyenDungDao();
            tintuyendungDao = new TinTuyenDungDao();
        }

        // GET: NhaTuyenDung/Home
        public ActionResult Index()
        {
            var userLogin = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            if (userLogin == null) return RedirectToAction("Index", "Login");
            ViewBag.SlTinTuyenDung = tintuyendungDao.SlTinTuyenDung(userLogin.Id, true);
            ViewBag.SlTinChoDuyet = tintuyendungDao.SlTinTuyenDung(userLogin.Id, false);
            ViewBag.SlBaiViet = new BaiVietDao().SlBaiViet(userLogin.Id, true);
            ViewBag.SlUngVien = new UngTuyenDao().SlUngTuyen(userLogin.Id);
            ViewBag.TopView = new TinTuyenDungDao().GetListTopView(5, userLogin.Id);
            return View();
        }

        public ActionResult Logout()
        {
            SetAlert("Đăng xuất thành công", "success");
            Session[CommonConstants.EMPLOYER_SESSION] = null;
            return RedirectToAction("Index", "Login");
        }

        public async Task<ActionResult> Info()
        {
            var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            if (session == null) return RedirectToAction("Index");
            var member = await nhatuyendungDao.GetByIdClient(session.Id);
            ViewBag.AnhDaiDien = member.AnhDaiDien;
            ViewBag.AnhBia = member.AnhBia;
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Info(EmployerEditClient member)
        {
            var item = await nhatuyendungDao.GetByIdClient(member.MaNTD);
            ViewBag.AnhDaiDien = item.AnhDaiDien;
            ViewBag.AnhBia = item.AnhBia;
            if (ModelState.IsValid)
            {
                var result = await nhatuyendungDao.UpdateClient(member, Server);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [ChildActionOnly]
        public ActionResult _SidebarMenu()
        {
            var userLogin = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            ViewBag.SlTinChoDuyet = tintuyendungDao.SlTinTuyenDung(userLogin.Id, false);
            ViewBag.BaiVietChuaDuyet = new BaiVietDao().SlBaiViet(userLogin.Id, false);
            return PartialView();
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class LoginController : Controller
    {
        private readonly TaiKhoanDao taiKhoanDao;

        public LoginController()
        {
            taiKhoanDao = new TaiKhoanDao();
        }

        // GET: Login
        public ActionResult Index()
        {
            Session[CommonConstants.EMPLOYER_SESSION] = null;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(Models.ViewModels.Employer.LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await taiKhoanDao.Login(model.Email, model.Password, CommonConstants.NHATUYENDUNG);
                if (result > 0)
                {
                    var userLogin = await taiKhoanDao.GetByEmail_NhaTuyenDung(model.Email);
                    Session[CommonConstants.EMPLOYER_SESSION] = userLogin;
                    TempData["Notify"] = "Đăng nhập thành công!";
                    TempData["AlertType"] = "alert-success";
                    return RedirectToAction("Index", "Home");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản đã bị khóa");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Sai tài khoản hoặc mật khẩu");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(Models.ViewModels.Employer.RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await taiKhoanDao.Register_NhaTuyenDung(model);
                if (result > 0)
                {
                    TempData["notify"] = "Đăng ký thành công !";
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Email này đã tồn tại");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Đã có lỗi xảy ra. Vui lòng thử lại");
                }
            }
            return View();
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/UngTuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.HoSoXinViec;
using TuyenDungCNTT.Models.ViewModels.UngTuyen;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class UngTuyenController : BaseController
    {
        private readonly UngTuyenDao ungTuyenDao;
        public UngTuyenController()
        {
            ungTuyenDao = new UngTuyenDao();
        }

        // GET: NhaTuyenDung/UngTuyen
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool status, int month, string keyWord,  int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = new UngTuyenDao().GetListByNTD(status, month, request, UserLogin().Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChuaXem()
        {
            return View();
        }

        public async Task<RedirectResult> XemCV(int maUV, int maTTD)
        {
            var link = await ungTuyenDao.UpdateStatus(maUV, maTTD);
            return RedirectPermanent(link);
        }

        public ActionResult TimUngVien()
        {
            return View();
        }

        public ActionResult DeXuat()
        {
            var model = new HoSoXinViecDao().DeXuatUngVien(UserLogin().Id);
            return View(model);
        }

        public ActionResult CapNhat(int maUV, int maTTD)
        {
            var model = ungTuyenDao.GetItem(maUV, maTTD);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CapNhat(int MaUngVien, int MaTTD, string trangThai)
        {
            var result = await ungTuyenDao.UpdateStatus(MaUngVien, MaTTD, trangThai);
            if (result)
            {
                SetAlert("Cập nhật thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return RedirectToAction("Index");
        }

        public JsonResult GetSearchPaging(string KeyWord, int pageIndex, string CapBac, string ChuyenNganh, string LoaiCV)
        {
            var request = new HoSoXinViecSearch()
            {
                CapBac = CapBac,
                ChuyenNganh = ChuyenNganh,
                LoaiCV = LoaiCV
            };

            var paging = new GetListPaging()
            {
                keyWord = KeyWord.ToLower(),
                PageIndex = pageIndex,
                PageSize = 5
            };
            var data = new HoSoXinViecDao().GetListSearch(paging, request);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / paging.PageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }
    }
}

TuyenDungCNTT/Areas/Admin/Views/NhaTuyenDung/Create.cshtml
@model TuyenDungCNTT.Models.ViewModels.Employer.EmployerEdit

@{
    ViewBag.Title = "Tạo nhà tuyển dụng mới";
    ViewBag.PrevPage = "Quản lý ứng tuyển";
    ViewBag.CurrentPage = "Tạo nhà tuyển dụng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Tạo nhà tuyển dụng mới</h4>
                </div>
                <div class="collapse pt-3 show">
                    @using (Html.BeginForm("Create", "NhaTuyenDung", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.MaNTD, "Mã nhà tuyển dụng", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.MaNTD, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                                    @Html.ValidationMessageFor(model => model.MaNTD, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.TenNTD, "Tên nhà tuyển dụng", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.TenNTD, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TenNTD, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.TenNDD, "Tên người đại diện", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.TenNDD, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TenNDD, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.ChucVuNDD, "Vị trí công tác", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.DropDownListFor(model => model.ChucVuNDD, new List<SelectListItem>()
                                    {
                                        new SelectListItem() {Value = null, Text = "-- Chọn vị trí công tác --"},
                                        new SelectListItem() {Value = "Nhân viên", Text = "Nhân viên"},
                                        new SelectListItem() {Value = "Trưởng nhóm", Text = "Trưởng nhóm"},
                                        new SelectListItem() {Value = "Trưởng phòng", Text = "Trưởng phòng"},
                                        new SelectListItem() {Value = "Phó phòng", Text = "Phó phòng"},
                                        new SelectListItem() {Value = "Phó giám đốc", Text = "Phó giảm đốc"},
                                        new SelectListItem() {Value = "Giám đốc", Text = "Giám đốc"}
                                    },
                                    new { @class = "form-control text-box single-line" })
                                    @Html.ValidationMessageFor(model => model.ChucVuNDD, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.SoDienThoai, "Số điện thoại", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.QuyMo, "Quy mô công ty", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.QuyMo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.QuyMo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.MoTa, "Mô tả", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.TextAreaFor(model => model.MoTa, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.DiaChi, "Địa chỉ", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.Website, "Tên website", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row mt-3">
                                <div class="col-md-2">
                                    @Html.ActionLink("Trở về", "Index", "UngVien", null, new { @class = "btn btn-light" })
                                </div>

                                <div class="col-md-6">
                                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TuyenDungCNTT/Areas/Admin/Views/NhaTuyenDung/Detail.cshtml
@model TuyenDungCNTT.Models.ViewModels.Employer.EmployerEdit

@{
    ViewBag.Title = "Thông tin nhà tuyển dụng";
    ViewBag.PrevPage = "Quản lý ứng tuyển";
    ViewBag.CurrentPage = "Thông tin nhà tuyển dụng '" + Model.TenNTD + "'";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Thông tin nhà tuyển dụng: @Model.TenNTD</h4>
                </div>
                <div class="collapse pt-3 show">
                    <div class="form-horizontal">

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.TenNTD, "Tên nhà tuyển dụng", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.TenNTD )
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.TenNDD, "Tên người đại diện", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.TenNDD)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.ChucVuNDD, "Vị trí công tác", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.ChucVuNDD)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.SoDienThoai, "Số điện thoại", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.SoDienThoai)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.QuyMo, "Quy mô công ty", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.QuyMo)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.MoTa, "Mô tả", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.MoTa)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DisplayTextFor(model => model.DiaChi)
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.Website, "Tên website", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                <a href="@Model.Website" target="_blank">@Model.Website</a>
                            </div>
                        </div>

                        <div class="form-group align-items-center row mt-3">
                            <div class="col-md-2">
                            </div>

                            <div class="col-md-6">
                                @Html.ActionLink("Trở về", "Index", "NhaTuyenDung", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>