TuyenDungCNTT/Models/ViewModels/BaiViet/BaiVietCreate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TuyenDungCNTT.Models.ViewModels.BaiViet
{
    public class BaiVietCreate
    {
        [Required(ErrorMessage = "Bạn chưa nhập tên bài viết")]
        public string TenBaiViet { get; set; }

        public string AnhChinh { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Bạn chưa nhập nội dung")]
        public string NoiDung { get; set; }
        
        public int MaTaiKhoan { get; set; }

        [Required(ErrorMessage = "Bạn chưa cập nhật trạng thái")]
        public bool TrangThai { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/BaiViet/BaiVietEdit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TuyenDungCNTT.Models.ViewModels.BaiViet
{
    public class BaiVietEdit
    {
        public int MaBaiViet { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên bài viết")]
        public string TenBaiViet { get; set; }

        public string AnhChinh { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Bạn chưa nhập nội dung")]
        public string NoiDung { get; set; }

        public string TenTacGia { get; set; }

        [Required(ErrorMessage = "Bạn chưa cập nhật trạng thái")]
        public bool TrangThai { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/BaiViet/BaiVietVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TuyenDungCNTT.Common;

namespace TuyenDungCNTT.Models.ViewModels.BaiViet
{
    public class BaiVietVm
    {
        public int MaBaiViet { get; set; }

        public string TenBaiViet { get; set; }
        public string TieuDe => StringHelper.ToUnsignString(TenBaiViet).ToLower();

        public string AnhChinh { get; set; }

        public string NoiDung { get; set; }

        public string TenTacGia { get; set; }

        public string ThoiGian { get; set; }

        public int? LuotXem { get; set; }

        public string TrangThai { get; set; }
    }
}

TuyenDungCNTT/Areas/Admin/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Areas.Admin.Models;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.BaiViet;
using TuyenDungCNTT.Models.ViewModels.Common;

namespace TuyenDungCNTT.Areas.Admin.Controllers
{
    public class BaiVietController : BaseController
    {
        private readonly BaiVietDao dao;

        public BaiVietController()
        {
            dao = new BaiVietDao();
        }

        // GET: Admin/BaiViet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool trangThai, string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var session = (AdminLogin)Session[CommonConstants.ADMIN_SESSION];
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = dao.GetList(request, trangThai, session.Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(BaiVietCreate member)
        {
            if (ModelState.IsValid)
            {
                var session = (AdminLogin)Session[CommonConstants.ADMIN_SESSION];
                var result = await dao.Create(member, Server, session.Id);
                if (result > 0)
                {
                    SetAlert("Tạo bài viết thành công", "success");
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tên bài viết đã tồn tại");
                }
                else
                {
                    SetAlert("Đã có lỗi xảy ra. Vui lòng thử lại", "error");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var member = await dao.GetById(id);
            ViewBag.MaBaiViet = member.MaBaiViet;
            ViewBag.AnhChinh = member.AnhChinh;
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(BaiVietEdit member)
        {
            var item = await dao.GetById(member.MaBaiViet);
            ViewBag.MaBaiViet = item.MaBaiViet;
            ViewBag.AnhChinh = item.AnhChinh;
            if (ModelState.IsValid)
            {
                var session = (AdminLogin)Session[CommonConstants.ADMIN_SESSION];
                var result = await dao.UpdateBaiViet(member, Server, session.Id);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maBaiViet)
        {
            var result = await dao.Delete(maBaiViet);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }

        public ActionResult ChoDuyet()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Duyet(int maBaiViet)
        {
            var result = await dao.Duyet(maBaiViet);
            if (result)
            {
                SetAlert("Duyệt thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.BaiViet;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.User;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class BaiVietController : BaseController
    {
        private readonly BaiVietDao dao;

        public BaiVietController()
        {
            dao = new BaiVietDao();
        }

        // GET: NhaTuyenDung/BaiViet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool trangThai, string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = dao.GetList(request, trangThai, session.Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(BaiVietCreate member)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.Create(member, Server, session.Id);
                if (result > 0)
                {
                    SetAlert("Tạo bài viết thành công", "success");
                    return RedirectToAction("Index");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tên bài viết đã tồn tại");
                }
                else
                {
                    SetAlert("Đã có lỗi xảy ra. Vui lòng thử lại", "error");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var member = await dao.GetById(id);
            ViewBag.MaBaiViet = member.MaBaiViet;
            ViewBag.AnhChinh = member.AnhChinh;
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(BaiVietEdit member)
        {
            var item = await dao.GetById(member.MaBaiViet);
            ViewBag.MaBaiViet = item.MaBaiViet;
            ViewBag.AnhChinh = item.AnhChinh;
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.UpdateBaiViet(member, Server, session.Id);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maBaiViet)
        {
            var result = await dao.Delete(maBaiViet);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }

        public ActionResult ChoDuyet()
        {
            return View();
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Views/BaiViet/ChoDuyet.cshtml
@{
    ViewBag.Title = "Bài viết chờ duyệt";
    ViewBag.PrevPage = "Bài viết";
    ViewBag.CurrentPage = "Bài viết chờ duyệt";
    Layout = "~/Areas/NhaTuyenDung/Views/Shared/_LayoutEmployer.cshtml";
}


@section scripts {
    <script src="~/Assets/Client/js/Employer/baiVietChoDuyet.js"></script>
    <script src="~/Assets/Admin/js/common.js"></script>
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-widgets py-2">
                    <a href="javascript: void(0);" data-toggle="reload"><i class="mdi mdi-refresh"></i></a>
                    <a data-toggle="collapse" href="#cardCollpase5" role="button" aria-expanded="false" aria-controls="cardCollpase5"><i class="mdi mdi-minus"></i></a>
                </div>


                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Danh sách bài viết chờ duyệt</h4>
                </div>

                <div id="cardCollpase5" class="collapse pt-3 show">
                    <div class="row my-1">
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter">
                                <label>
                                    Hiện <select id="selection-datatable_length" name="selection-datatable_length" aria-controls="selection-datatable" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="15">15</option>
                                        <option value="20">20</option>
                                    </select> mục / trang
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter text-right">
                                <label>
                                    Tìm kiếm:
                                    <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="selection-datatable" id="txtsearch">
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-centered mb-0" id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Mã bài viết</th>
                                    <th>Ảnh chính</th>
                                    <th>Tên bài viết</th>
                                    <th>Tên tác giả</th>
                                    <th>Ngày đăng</th>
                                    <th>Lượt xem</th>
                                    <th>Trạng thái</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>

                    <div class="row align-items-center mt-2">
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info" id="selection-datatable_info" role="status" aria-live="polite"></div>
                        </div>
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="selection-datatable_paginate">
                                <ul class="pagination pagination-rounded m-0 justify-content-end" id="load-pagination">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>

TuyenDungCNTT/Areas/NhaTuyenDung/Views/BaiViet/Create.cshtml
@model TuyenDungCNTT.Models.ViewModels.BaiViet.BaiVietCreate

@{
    ViewBag.Title = "Đăng bài viết mới";
    ViewBag.PrevPage = "Bài viết";
    ViewBag.CurrentPage = "Tạo bài viết";
    Layout = "~/Areas/NhaTuyenDung/Views/Shared/_LayoutEmployer.cshtml";
}

@section scripts {
    <script src="~/Assets/Plugins/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("txtNoiDung");
    </script>
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Tạo bài viết</h4>
                </div>
                <div class="collapse pt-3 show">
                    @using (Html.BeginForm("Create", "BaiViet", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.TenBaiViet, "Tên bài viết", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.TextAreaFor(model => model.TenBaiViet, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TenBaiViet, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.AnhChinh, "Ảnh chính", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    <input name="Image" type="file" accept="image/*" />
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.NoiDung, "Nội dung", new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NoiDung, new { @class = "form-control", id = "txtNoiDung" })
                                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row mt-3">
                                <div class="col-md-2">
                                    @Html.ActionLink("Trở về", "Index", "BaiViet", null, new { @class = "btn btn-light" })
                                </div>

                                <div class="col-md-6">
                                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TuyenDungCNTT/Areas/NhaTuyenDung/Views/BaiViet/Edit.cshtml
@model TuyenDungCNTT.Models.ViewModels.BaiViet.BaiVietEdit

@{
    ViewBag.Title = "Sửa thông tin bài viết";
    ViewBag.PrevPage = "Bài viết";
    ViewBag.CurrentPage = "Sửa bài viết";
    Layout = "~/Areas/NhaTuyenDung/Views/Shared/_LayoutEmployer.cshtml";
}


@section scripts {
    <script src="~/Assets/Plugins/ckeditor/ckeditor.js"></script>

    <script>
        var editor = CKEDITOR.replace("txtNoiDung");

        $('#Image').change(() => {
            $('#image_update').css('display', 'none');
        })
    </script>
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Sửa thông tin bài viết mã số: @ViewBag.MaBaiViet</h4>
                </div>
                <div class="collapse pt-3 show">
                    @using (Html.BeginForm("Edit", "BaiViet", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.MaBaiViet)

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.TenBaiViet, "Tên bài viết", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.TextAreaFor(model => model.TenBaiViet, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TenBaiViet, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.AnhChinh, "Ảnh chính", new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @if (ViewBag.AnhChinh != null)
                                    {
                                        <div class="mb-1" id="image_update">
                                            <img src="@ViewBag.AnhChinh" width="150" height="100" />
                                        </div>
                                    }
                                    <input name="Image" id="Image" type="file" accept="image/*" />
                                </div>
                            </div>

                            <div class="form-group align-items-center row">
                                @Html.LabelFor(model => model.NoiDung, "Nội dung", new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NoiDung, new { @class = "form-control", id = "txtNoiDung" })
                                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group align-items-center row mt-3">
                                <div class="col-md-2">
                                    @Html.ActionLink("Trở về", "Index", "BaiViet", null, new { @class = "btn btn-light" })
                                </div>

                                <div class="col-md-6">
                                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TuyenDungCNTT/Areas/NhaTuyenDung/Views/BaiViet/Index.cshtml
@{
    ViewBag.Title = "Danh sách bài viết";
    ViewBag.PrevPage = "Bài viết";
    ViewBag.CurrentPage = "Bài viết của bạn";
    Layout = "~/Areas/NhaTuyenDung/Views/Shared/_LayoutEmployer.cshtml";
}

@section scripts {
    <script src="~/Assets/Client/js/Employer/baiViet.js"></script>
    <script src="~/Assets/Admin/js/common.js"></script>
}

<div class="row">
    <div class="col-xl-12">

        <div class="card">
            <div class="card-body">
                <div class="card-widgets py-2">
                    <a href="javascript: void(0);" data-toggle="reload"><i class="mdi mdi-refresh"></i></a>
                    <a data-toggle="collapse" href="#cardCollpase5" role="button" aria-expanded="false" aria-controls="cardCollpase5"><i class="mdi mdi-minus"></i></a>
                </div>


                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Danh sách bài viết</h4>
                </div>

                <div id="cardCollpase5" class="collapse pt-3 show">
                    <div class="row my-1">
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter">
                                <label>
                                    Hiện <select id="selection-datatable_length" name="selection-datatable_length" aria-controls="selection-datatable" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="15">15</option>
                                        <option value="20">20</option>
                                    </select> mục / trang
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter text-right">
                                <label>
                                    Tìm kiếm:
                                    <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="selection-datatable" id="txtsearch">
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-centered mb-0" id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Mã bài viết</th>
                                    <th>Ảnh</th>
                                    <th>Tên bài viết</th>
                                    <th>Tên tác giả</th>
                                    <th>Ngày đăng</th>
                                    <th>Lượt xem</th>
                                    <th>Trạng thái</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>

                    <div class="row align-items-center mt-2">
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info" id="selection-datatable_info" role="status" aria-live="polite"></div>
                        </div>
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="selection-datatable_paginate">
                                <ul class="pagination pagination-rounded m-0 justify-content-end" id="load-pagination">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>