TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungCreate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungCreate
    {
        [Required(ErrorMessage = "Chưa nhập tên công việc")]
        [MaxLength(length: 250, ErrorMessage = "Nên đặt tên công việc dưới 250 ký tự")]
        public string TenCongViec { get; set; }

        [Required(ErrorMessage = "Chưa chọn chuyên ngành")]
        public string MaCN { get; set; }

        [Required(ErrorMessage = "Chưa chọn loại công việc")]
        public string MaLoaiCV { get; set; }

        [Required(ErrorMessage = "Chưa chọn mức lương")]
        public string MaMucLuong { get; set; }

        [Required(ErrorMessage = "Chưa chọn cấp bậc")]
        public string MaCapBac { get; set; }

        [Required(ErrorMessage = "Chưa nhập địa chỉ làm việc")]
        public string MaDiaChi { get; set; }

        public string DiaChiLamViec { get; set; }

        public int? SoLuong { get; set; }

        [Required(ErrorMessage = "Chưa chọn yêu cầu giới tính")]
        public string GioiTinhYC { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Chưa nhập mô tả công việc")]
        public string MoTaCongViec { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Chưa nhập yêu cầu ứng viên")]
        public string YeuCauUngVien { get; set; }

        [AllowHtml]
        public string KyNangLienQuan { get; set; }

        [AllowHtml]
        public string QuyenLoi { get; set; }

        [Required(ErrorMessage = "Chưa nhập hạn nộp")]
        public DateTime? HanNop { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungEdit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungEdit
    {
        public int MaTTD { get; set; }

        [Required(ErrorMessage = "Chưa nhập tên công việc")]
        [MaxLength(length: 250, ErrorMessage = "Nên đặt tên công việc dưới 250 ký tự")]
        public string TenCongViec { get; set; }

        [Required(ErrorMessage = "Chưa chọn chuyên ngành")]
        public string MaCN { get; set; }

        [Required(ErrorMessage = "Chưa chọn loại công việc")]
        public string MaLoaiCV { get; set; }

        [Required(ErrorMessage = "Chưa chọn mức lương")]
        public string MaMucLuong { get; set; }

        [Required(ErrorMessage = "Chưa chọn cấp bậc")]
        public string MaCapBac { get; set; }

        [Required(ErrorMessage = "Chưa nhập địa chỉ làm việc")]
        public string MaDiaChi { get; set; }

        public string DiaChiLamViec { get; set; }

        public int? SoLuong { get; set; }

        [Required(ErrorMessage = "Chưa chọn yêu cầu giới tính")]
        public string GioiTinhYC { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Chưa nhập mô tả công việc")]
        public string MoTaCongViec { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Chưa nhập yêu cầu ứng viên")]
        public string YeuCauUngVien { get; set; }

        [AllowHtml]
        public string KyNangLienQuan { get; set; }

        [AllowHtml]
        public string QuyenLoi { get; set; }

        [Required(ErrorMessage = "Chưa nhập hạn nộp")]
        public string HanNop { get; set; }
        public bool TrangThai { get; set; }

        [AllowHtml]
        public string GhiChu { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungLuu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TuyenDungCNTT.Common;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungLuu
    {
        public int MaTTD { get; set; }
        public int MaNTD { get; set; }
        public string TenNTD { get; set; }
        public string TieuDeNTD => StringHelper.ToUnsignString(TenNTD).ToLower();
        public string AnhDaiDien { get; set; }
        public string TenCongViec { get; set; }
        public string TieuDeTTD => StringHelper.ToUnsignString(TenCongViec).ToLower();
        public string LoaiCV { get; set; }
        public string MucLuong { get; set; }
        public string DiaChi { get; set; }
        public string NgayDang { get; set; }
        public string HanNop { get; set; }
        public string NgayUngTuyen { get; set; }
        public string TrangThai { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungSearch
    {
        public string CapBac { get; set; }
        public string DiaChi { get; set; }
        public string ChuyenNganh { get; set; }
        public string LoaiCV { get; set; }
        public string MucLuong { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TuyenDungCNTT.Common;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungVm
    {
        public int MaTTD { get; set; }

        public string TenNTD { get; set; }

        public string TenCongViec { get; set; }
        public string TieuDeTTD => StringHelper.ToUnsignString(TenCongViec).ToLower();

        public int? SoLuong { get; set; }

        public string NgayDang { get; set; }

        public string HanNop { get; set; }

        public int? LuotXem { get; set; }

        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungVmDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TuyenDungCNTT.Common;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungVmDetail
    {
        public int MaTTD { get; set; }
        public string TieuDeTTD => StringHelper.ToUnsignString(TenCongViec).ToLower();
        public string TenNTD { get; set; }
        public int MaNTD { get; set; }
        public string TieuDeNTD => StringHelper.ToUnsignString(TenNTD).ToLower();
        public string MoTa { get; set; }
        public string QuyMo { get; set; }
        public string DiaChiNTD { get; set; }
        public string AnhDaiDien { get; set; }
        public string TenCongViec { get; set; }
        public string ChuyenNganh { get; set; }
        public string LoaiCV { get; set; }
        public string MucLuong { get; set; }
        public string DiaChi { get; set; }
        public string DiaChiLamViec { get; set; }
        public string CapBac { get; set; }
        public int SoLuong { get; set; }
        public string GioiTinhYC { get; set; }
        public string MoTaCongViec { get; set; }
        public string YeuCauUngVien { get; set; }
        public string KyNangLienQuan { get; set; }
        public string QuyenLoi { get; set; }
        public string HanNop { get; set; }
    }
}

TuyenDungCNTT/Models/ViewModels/TinTuyenDung/TinTuyenDungVmHome.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TuyenDungCNTT.Common;

namespace TuyenDungCNTT.Models.ViewModels.TinTuyenDung
{
    public class TinTuyenDungVmHome
    {
        public int MaTTD { get; set; }
        public int MaNTD { get; set; }
        public string TenNTD { get; set; }
        public string TieuDeNTD => StringHelper.ToUnsignString(TenNTD).ToLower();
        public string AnhDaiDien { get; set; }
        public string TenCongViec { get; set; }
        public string TieuDeTTD => StringHelper.ToUnsignString(TenCongViec).ToLower();
        public string LoaiCV { get; set; }
        public string MucLuong { get; set; }
        public string DiaChi { get; set; }
        public string NgayDang { get; set; }
        public string HanNop { get; set; }
    }
}

TuyenDungCNTT/Areas/Admin/Controllers/TinTuyenDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Areas.Admin.Models;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.TinTuyenDung;

namespace TuyenDungCNTT.Areas.Admin.Controllers
{
    public class TinTuyenDungController : BaseController
    {
        private readonly TinTuyenDungDao dao;

        public TinTuyenDungController()
        {
            dao = new TinTuyenDungDao();
        }

        // GET: Admin/TinTuyenDung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool trangThai, string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var session = (AdminLogin)Session[CommonConstants.ADMIN_SESSION];
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = dao.GetList(false, request, trangThai, session.Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult TinChoDuyet()
        {
            return View();
        }

        public async Task<ActionResult> Edit(int id)
        {
            var member = await dao.GetById(id);
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(TinTuyenDungEdit member)
        {
            if (ModelState.IsValid)
            {
                var session = (AdminLogin)Session[CommonConstants.ADMIN_SESSION];
                var result = await dao.EditTTD(member, session.Id);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public ActionResult ChoDuyet()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Duyet(int maTTD)
        {
            var result = await dao.Duyet(maTTD);
            if (result)
            {
                SetAlert("Duyệt thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maTTD)
        {
            var result = await dao.Delete(maTTD);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }
    }
}

TuyenDungCNTT/Areas/NhaTuyenDung/Controllers/TinTuyenDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TuyenDungCNTT.Common;
using TuyenDungCNTT.Models.Dao;
using TuyenDungCNTT.Models.ViewModels.Common;
using TuyenDungCNTT.Models.ViewModels.TinTuyenDung;
using TuyenDungCNTT.Models.ViewModels.User;

namespace TuyenDungCNTT.Areas.NhaTuyenDung.Controllers
{
    public class TinTuyenDungController : BaseController
    {
        private readonly TinTuyenDungDao dao;
        public TinTuyenDungController()
        {
            dao = new TinTuyenDungDao();
        }

        // GET: NhaTuyenDung/TinTuyenDung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(bool? hetHan, bool trangThai, string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
            var request = new GetListPaging()
            {
                keyWord = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = dao.GetList(hetHan, request, trangThai, session.Id);
            int totalRecord = data.TotalRecord;
            int toalPage = (int)Math.Ceiling((double)totalRecord / pageSize);
            return Json(new { data = data.Items, pageCurrent = pageIndex, toalPage = toalPage, totalRecord = totalRecord }
                , JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChoDuyet()
        {
            return View();
        }

        public ActionResult HetHan()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(TinTuyenDungCreate item)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.Create(item, session.Id);
                if (result > 0)
                {
                    SetAlert("Tạo tin tuyển dụng thành công", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    SetAlert("Đã có lỗi xảy ra. Vui lòng thử lại", "error");
                }
            }
            return View();
        }

        public async Task<ActionResult> Edit(int id)
        {
            var member = await dao.GetById(id);
            return View(member);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(TinTuyenDungEdit member)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstants.EMPLOYER_SESSION];
                var result = await dao.EditTTD(member, session.Id);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int maTTD)
        {
            var result = await dao.Delete(maTTD);
            if (result)
            {
                SetAlert("Xóa thành công", "success");
            }
            else
            {
                SetAlert("Có lỗi xảy ra. Vui lòng thử lại!", "error");
            }
            return Json(result);
        }
    }
}

TuyenDungCNTT/Areas/Admin/Views/TinTuyenDung/Edit.cshtml
@model TuyenDungCNTT.Models.ViewModels.TinTuyenDung.TinTuyenDungEdit
@using TuyenDungCNTT.Models.Dao

@{
    TinTuyenDungDao dao = new TinTuyenDungDao();
    var listCapBac = dao.ListCapBac();
    var listChuyenNganh = dao.ListChuyenNganh();
    var listLoaiCV = dao.ListLoaiCV();
    var listMucLuong = dao.ListMucLuong();
    var listDiaChi = dao.ListDiaChi();

    ViewBag.Title = "Sửa tin tuyển dụng";
    ViewBag.PrevPage = "Quản lý tin tuyển dụng";
    ViewBag.CurrentPage = "Sửa tin tuyển dụng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section scripts {
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Assets/Plugins/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("txtMoTa");
        CKEDITOR.replace("txtYeuCau");
        CKEDITOR.replace("txtKyNang");
        CKEDITOR.replace("txtQuyenLoi");
        CKEDITOR.replace("txtGhiChu");
    </script>
}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Đăng tin tuyển dụng</h4>
                </div>
                <div class="collapse pt-3 show">
                    @using (Html.BeginForm("Edit", "TinTuyenDung", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.MaTTD)

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.TenCongViec, "Tên công việc", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextAreaFor(model => model.TenCongViec, new { @class = "form-control", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.MaCapBac, "Cấp bậc", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.MaCapBac, new SelectList(listCapBac, "PK_sMaCapBac", "sTenCapBac"), "-- Chọn cấp bậc --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                            @Html.LabelFor(model => model.MaCN, "Chuyên ngành", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.MaCN, new SelectList(listChuyenNganh, "PK_sMaCN", "sTenCN"), "-- Chọn chuyên ngành --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.MaLoaiCV, "Loại công việc", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.MaLoaiCV, new SelectList(listLoaiCV, "PK_sMaLoaiCV", "sTenLoaiCV"), "-- Chọn hình thức làm việc --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                            @Html.LabelFor(model => model.MaDiaChi, "Địa chỉ", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.MaDiaChi, new SelectList(listDiaChi, "PK_sMaDiaChi", "sTenDiaChi"), "-- Chọn địa chỉ --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.MaMucLuong, "Mức lương", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.MaMucLuong, new SelectList(listMucLuong, "PK_sMaMucLuong", "sTenMucLuong"), "-- Chọn mức lương --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                            @Html.LabelFor(model => model.GioiTinhYC, "Giới tính", new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.GioiTinhYC, new List<SelectListItem>()
                                {
                                    new SelectListItem() {Value = "Nam", Text = "Nam"},
                                    new SelectListItem() {Value = "Nữ", Text = "Nữ"},
                                    new SelectListItem() {Value = "Không yêu cầu", Text = "Không yêu cầu"}
                                }, "-- Chọn giới tính yêu cầu --", new { @class = "form-control text-box single-line selectpicker", @data_live_search = "true", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.DiaChiLamViec, "Địa chỉ làm việc", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.DiaChiLamViec, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.MoTaCongViec, "Mô tả công việc", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.MoTaCongViec, new { @class = "form-control", id = "txtMoTa", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.YeuCauUngVien, "Yêu cầu ứng viên", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.YeuCauUngVien, new { @class = "form-control", id = "txtYeuCau", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.KyNangLienQuan, "Kỹ năng liên quan", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.KyNangLienQuan, new { @class = "form-control", id = "txtKyNang", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.QuyenLoi, "Quyền lợi", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.QuyenLoi, new { @class = "form-control", id = "txtQuyenLoi", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.SoLuong, "Số lượng tuyển", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.SoLuong, new { @class = "form-control", @type = "number", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.HanNop, "Hạn nộp", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.HanNop, new { @class = "form-control", @type = "datetime-local", @readonly = "true" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.TrangThai, "Trạng thái", new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.TrangThai, new List<SelectListItem>()
                                {
                                    new SelectListItem() {Value = "true", Text = "Duyệt tin"},
                                    new SelectListItem() {Value = "false", Text = "Chờ xác nhận"}
                                }, "-- Chọn trạng thái --",
                                new { @class = "form-control text-box single-line" })
                                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row">
                            @Html.LabelFor(model => model.GhiChu, "Ghi chú", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.GhiChu, new { @class = "form-control", id = "txtGhiChu" })
                            </div>
                        </div>

                        <div class="form-group align-items-center row mt-3">
                            <div class="col-md-2">
                                @Html.ActionLink("Trở về", "Index", "TinTuyenDung", null, new { @class = "btn btn-light" })
                            </div>

                            <div class="col-md-6">
                                <input type="submit" value="Cập nhật" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                     }
                </div>
            </div>
        </div>
    </div>
</div>

TuyenDungCNTT/Areas/Admin/Views/TinTuyenDung/Index.cshtml
@{
    ViewBag.Title = "Danh sách tin tuyển dụng";
    ViewBag.PrevPage = "Quản lý tuyển dụng";
    ViewBag.CurrentPage = "Danh sách tin tuyển dụng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section scripts {
    <script src="~/Assets/Admin/js/tintuyendungController.js"></script>
    <script src="~/Assets/Admin/js/common.js"></script>
}

<div class="row">
    <div class="col-xl-12">

        <div class="card">
            <div class="card-body">
                <div class="card-widgets py-2">
                    <a href="javascript: void(0);" data-toggle="reload"><i class="mdi mdi-refresh"></i></a>
                    <a data-toggle="collapse" href="#cardCollpase5" role="button" aria-expanded="false" aria-controls="cardCollpase5"><i class="mdi mdi-minus"></i></a>
                </div>


                <div class="card-header py-2">
                    <h4 class="header-title mb-0">Danh sách bài viết</h4>
                </div>

                <div id="cardCollpase5" class="collapse pt-3 show">
                    <div class="row my-1">
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter">
                                <label>
                                    Hiện <select id="selection-datatable_length" name="selection-datatable_length" aria-controls="selection-datatable" class="custom-select custom-select-sm form-control form-control-sm">
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="15">15</option>
                                        <option value="20">20</option>
                                    </select> mục / trang
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_filter text-right">
                                <label>
                                    Tìm kiếm:
                                    <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="selection-datatable" id="txtsearch">
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-centered mb-0" id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Mã tin</th>
                                    <th>Tên công việc</th>
                                    <th>Nhà tuyển dụng</th>
                                    <th>Số lượng tuyển</th>
                                    <th>Ngày đăng</th>
                                    <th>Hạn nộp</th>
                                    <th>Lượt xem</th>
                                    <th>Trạng thái</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>

                    <div class="row align-items-center mt-2">
                        <div class="col-sm-12 col-md-5">
                            <div class="dataTables_info" id="selection-datatable_info" role="status" aria-live="polite"></div>
                        </div>
                        <div class="col-sm-12 col-md-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="selection-datatable_paginate">
                                <ul class="pagination pagination-rounded m-0 justify-content-end" id="load-pagination">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div> 
</div>